### ISSUE TITLE
Allow local network traffic as an optional flag

### ISSUE THREAD

**Issue by jongittoes** [vpn-kill-switch/killswitch#10]
By default killswitch blocks local network traffic, this is problematic for me and probably some other users. I would like to add a flag (-l) that would allow local network traffic. Is this in the pipeline or can I go ahead with it?

The action would be to add the following line to the killswitch.pf.conf:
pass on $int_en0 to $int_en0:network

and possibly then remove the dhcp/bootp lines as they would become superfluous

**Comment by nbari** [comment]
This is indeed the idea of the kill-switch, to block everything not going through the vpn,  modifying or giving options to add or excluded networks will put in risk inexperienced users.

**Comment by jongittoes** [comment]
The above pf rule only allows access to the local subnet, you can't get out of the local network with it. My reason for suggesting this is that if you are at home or at the office, ie a place that is trusted, you might want local network access.
In my case, with killswitch enabled, I cannot ssh to local servers, access Sonos on my local network, print locally etc.
I appreciate the potential danger for allowing this traffic on a public wifi and agree that there should be a warning in the help etc  but currently there is no way to achieve this using killswitch, the only solution is to create your own pf.conf and IMHO that opens up more risk to inexperienced users than adding it as a properly documented flag.
What do you think?

**Comment by nbari** [comment]
It breaks the idea behind the project,  for your special needs would be better to have your own  set of rules.

**Comment by jongittoes** [comment]
OK no problem

**Comment by nbari** [comment]
Just in case check this  https://github.com/vpn-kill-switch/killswitch/issues/4

**Comment by nbari** [comment]
https://github.com/vpn-kill-switch/killswitch/issues/13 related (work in progress)
