### ISSUE TITLE
Exit 0 if non root

### ISSUE THREAD

**Issue by jongittoes** [vpn-kill-switch/killswitch#11]
If killswitch is run with insufficient permission, ie non-root, it still returns exit 0, indicating no error.
Can you change it to return a non-zero exit code so this can be captured problematically?

**Comment by nbari** [comment]
Hi @jongittoes if run as non-root still gives you info about your current IP and interfaces, in case you have the VPN up and running and did't use `sudo` it will exit 1

**Comment by nbari** [comment]
I will fix to return error to `stderr` probably is what you mean, right?

**Comment by nbari** [comment]
Hi @jongittoes did some error messages improved, please give a try to `0.5.1`, thanks for catching this out.

**Comment by jongittoes** [comment]
Great, that is working now.
Just my opinion, I would remove the 'exit status 1' and perhaps be a bit clearer, something like:

###  Kill switch is not enabled, to enable use: sudo killswitch -e

Thanks

**Comment by nbari** [comment]
@jongittoes give a try just applied the changes.
