### ISSUE TITLE
Always allow access to local network

### ISSUE THREAD

**Issue by kabouzeid** [vpn-kill-switch/killswitch#13]

**Comment by nbari** [comment]
Any ideas about how to implement this? what abut probably have a file  `allowed` and probably use it with something like: 

    killswitch -a my-allowed-networks

**Comment by kabouzeid** [comment]
Isn’t there a way to automatically determine the local network? I think by default `killswitch -e` should allow local network traffic.

**Comment by nbari** [comment]
that will break the purpose of the kill switch since ideally you just want to allow traffic through the VPN, but maybe with other option (to be safe) the user will be aware of adding/allowing the local network, what do you think?

**Comment by nbari** [comment]
That is indeed another purpose,  I will try to add option `-a` with option to add local networks plus reading from a file, keeping as default the current settings mainly to make user aware of what is opening and probably “liks”.

You have a good point from a specific use case but when having also private networks (same as your lan) from the VPN, adds more complexity.

Any ideas about how to improve this are more than welcome

**Comment by kabouzeid** [comment]
Makes sense. Out of curiosity, what are you using the killswitch for?

**Comment by nbari** [comment]
mainly to prevent leaks from  VPN clients (http://vpn-kill-switch.com/about/) that may occasionally crash, (better safe than sorry).

**Comment by kabouzeid** [comment]
https://github.com/vpn-kill-switch/killswitch/pull/14

**Comment by nbari** [comment]
implemented in new 0.6.0

**Comment by kabouzeid** [comment]
Awesome, thanks for the quick review!
