### ISSUE TITLE
Enable even without VPN interface

### ISSUE THREAD

**Issue by whatthehomepod** [vpn-kill-switch/killswitch#18]
Please add enable to manually enable the kill switch until's it's manually turned off.
This because I'm using a mini router especially for VPN and/or TOR. However, this is just using the Wi-Fi and not the VPN interface native. I want this to use because I don't want to leak BEFORE I'm actually connected to the VPN/TOR.

**Comment by nbari** [comment]
hi @whatthehomepod can you please elaborate more on this, currently the `killswitch` is enabled only if you use the option `-e` and disabled with option `-d`.

Or you just want to pass your peer ip (option `-ip`) en either are connected or not to a VPN enable the VPN, for example something like:

    killswitch -e -ip 192.168.1.3 -f 

In where `-f` could be a new flag (force) enabling the firewall either local VPN is active or not?

**Comment by nbari** [comment]
hi @whatthehomepod can you please elaborate more on this, currently the `killswitch` is enabled only if you use the option `-e` and disabled with option `-d`.

Or you just want to pass your peer IP (option `-ip`), this requires VPN up and running first.

    killswitch -e -ip 192.168.1.3

**Comment by whatthehomepod** [comment]
> hi @whatthehomepod can you please elaborate more on this, currently the `killswitch` is enabled only if you use the option `-e` and disabled with option `-d`.
> 
> Or you just want to pass your peer IP (option `-ip`), this requires VPN up and running first.
> 
> ```
> killswitch -e -ip 192.168.1.3
> ```

I know however your script listens to the VPN interface and couldn't see whether I'm connected straight through the mini router. To implement THAT could be a lot of work, however you could build an option to always kill the connection and enable it only when connected to a new network for example. Or build an option to kill all services, instead http/https.

**Comment by nbari** [comment]
@whatthehomepod probably you need other tools, mechanisms,   the `killswitch`will only  stop network trafic when VPN goes down, it is not designed to  "kill connections" or only allow http/https trafic.

My guess is that you want to ensure that you http trafic goes out using your router the one is using TOR, probably the easies way is to configure your browser proxy setttings to only use your router, and have a killswitch on your router.
