### ISSUE TITLE
submit formula to homebrew (need stars)

### ISSUE THREAD

**Issue by nbari** [vpn-kill-switch/killswitch#20]
submit the brew formula into main homebrew repository in order to just use:

    brew install killswitch

need > 75 :star:

**Comment by javatarz** [comment]
Would be easier to fix this by setting up a github build pipeline to publish the artifact to github and then download from homebrew. Homebrew's requirements of binaries is way lower than source code for security reasons.

**Comment by javatarz** [comment]
I need to have more access to build the actions pipeline. I'd be happy to do it if you can give me temporary access.

**Comment by nbari** [comment]
Hi, there is already a formula but I  think current problem seems to be the lack of missing stars, how by using the pipeline could it help in this case?

**Comment by javatarz** [comment]
The formula works by building the code from source. For security reasons, the repository needs to have a certain number of forks and stars.

If you have a published artifact (binary), you wouldn't need 75 stars. For this, a build pipeline is needed (that compiles the code, creates a binary and stores the binary somewhere. This could either be done [manually](https://help.github.com/en/articles/creating-releases) or via a pipeline (on travis or github actions).

Doing either requires access. If you can upload an artifact into github's by creating a release (either manually or via a pipeline), I think you don't need to provide a git repo.

**Comment by nbari** [comment]
If I am properly understanding by just creating the pipeline you are saying that it would simplify the formula by instead of compiling will just use the binaries but how that changes or helps later to have the package installed by just doing `brew install killswitch` from my understanding either providing binaries or source formula needs to be accepted and merged into the brew repository, please correct me if not.

**Comment by nbari** [comment]
https://github.com/Homebrew/homebrew-core/pull/50775/files
