### ISSUE TITLE
Inconsistencies in killswitch

### ISSUE THREAD

**Issue by spatocode** [vpn-kill-switch/killswitch#22]
Hi! Thanks for the good work on this.

I have an issue with this tool. When i call ```killswitch -e``` from my VPN code, i got this error from my terminal.

```No VPN interface found, verify VPN is connected```

Do this mean i need to connect to VPN first before killswitch will work? However, when i call ```killswitch -e``` from my terminal, it works perfect without any errors.

**Comment by nbari** [comment]
hi @spatocode yes, you first need to connect your VPN or pass an IP, for example:

    killswitch -e -ip X.X.X.X

**Comment by spatocode** [comment]
OK, thanks! I will close this now.
