### ISSUE TITLE
Will this work reliably on the M1 Macs?

### ISSUE THREAD

**Issue by pnewell** [vpn-kill-switch/killswitch#25]
Just want to confirm this works fine on the new M1 Macs and that it won't leak my IP given all the changes? Are you planning on updating the app to work natively with them?

**Comment by nbari** [comment]
hi @pnewell  the big dependency is [pf](https://en.wikipedia.org/wiki/PF_(firewall)), now even in a Hackintosh it works, no matter what architecture you are using, but as always please test.

In case you have an M1 try `brew install killswitch` it should be working.(https://formulae.brew.sh/formula/killswitch)
