### ISSUE TITLE
WiFi and Ethernet - blocking one, not the other

### ISSUE THREAD

**Issue by jandreaucodes** [vpn-kill-switch/killswitch#27]
My desktop has an internet connection from WiFi and Ethernet. 

My VPN is running on the WiFi connection. 

When I run killswitch, it immediately blocks all traffic on the Ethernet port (which my machine reports as en0, the WiFi is en1).

How can I get killswitch to only look at my en2 network interface? I want to allow traffic through my Ethernet connection, but monitor my WiFi for the VPN disconnecting.

**Comment by nbari** [comment]
Hi, the `killswitch` will only allow traffic through your VPN, If you want to allow trafic on other interfaces you will need to modify the firewall rules, check: https://vpn-kill-switch.com/post/pf/
