### ISSUE TITLE
Doesn't block all traffic

### ISSUE THREAD

**Issue by Vanhecke** [vpn-kill-switch/killswitch#4]
Hello sir,

I like the concept of this thing bit it doesn't seem to block "all" traffic.
For example it doesn't block ICMP traffic as illustrated in the gif.
![untitled](https://user-images.githubusercontent.com/3396438/28325319-cc3a3de8-6bdd-11e7-981f-c7d9712f391a.gif)

**Comment by nbari** [comment]
Hi @Vanhecke thanks for testing and for the very nice gif that you just submit, regarding your  comment, that's correct, ICMP (ping) traffic is not blocked same as:
    
    multicast   224.0.0.0/4
    dhcp        ports 67:68
    broadcast   255.255.255.255

The idea of doing this is that you may want to send mainly tcp/udp traffic through the VPN, but still access your NAS or local network devices besides keeping your DHCP connection up, and probably been available to ping within your network.

In any case, you could disable it by  commenting put the rule located in this file after starting the killswitch:` /tmp/killswitch.pf.conf`, comment the line containing: 

    inet proto icmp all icmp-type 8

and then just reload the rules by doing this:  

    sudo pfctl -Fa -f /tmp/killswitch.pf.conf

**Comment by Vanhecke** [comment]
Ok, that makes sense.
Thanks for the info.
