### ISSUE TITLE
make: dep: No such file or directory

### ISSUE THREAD

**Issue by niclasek** [vpn-kill-switch/killswitch#7]
Hi, I tried to build this tool but I got an error. Do you know why?

~/go/src/github.com/vpn-kill-switch/killswitch$ make
dep ensure
make: dep: No such file or directory
make: *** [get] Error 1

Regards
Niclas

**Comment by nbari** [comment]
Hi @niclasek you need to have `dep`:

    brew install dep

or you could just do `go get` and later `make build` give a try and let me know

**Comment by nbari** [comment]
I just fix the Makefile to not depend on `dep` please give a try should be working now

**Comment by niclasek** [comment]
It does. Thank you!
