### ISSUE TITLE
DNS leak

### ISSUE THREAD

**Issue by jeffrey182** [vpn-kill-switch/killswitch#8]
The PF rule for port 53 will allow DNS queries when VPN goes down.  DNS can leak with VPN down.

**Comment by nbari** [comment]
Hi @jeffrey182 that's partially correct also some other services, check this other issue https://github.com/vpn-kill-switch/killswitch/issues/4

At the end depends on how you set /configure your resolvers but the reason to keep it open is that could be that your VPN provider will not provide DNS's and you could stop resolving.

**Comment by jeffrey182** [comment]
Thanks!  I will configure as you suggested in issue #4.  It does seem to me that stopping resolving and other services is the expected and desired behavior of triggering a kill switch.

**Comment by nbari** [comment]
Hi @jeffrey182 if is ok for you I will close this, if found something else please create a new one.

**Comment by nbari** [comment]
Hi @jeffrey182, just in case latest version 0.5.0 blocks by default ping + DNS
