### ISSUE TITLE
Block non VPN DNS as an optional flag

### ISSUE THREAD

**Issue by jongittoes** [vpn-kill-switch/killswitch#9]
I think it would be useful to have this as an optional flag, ie -D block any non VPN DNS requests. 
Is this in the pipeline or is it ok for me to do it and if so any preference on the flag?
The only action would be to not include the two config lines for port 53.

**Comment by nbari** [comment]
Hi, currently there are no plans to implement it, but please feel free to contribute.

**Comment by nbari** [comment]
hi @jongittoes check the development version, I just added flat `-paranoid` it disables ping and DNS.

**Comment by jongittoes** [comment]
Awesome, works a treat!
Thanks
